package com.yungou.o2o.center.manager.model;

import java.io.Serializable;
import java.util.Date;

public class Activity implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -1132320182500335484L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.Id:���
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.goods_id:��ƷID
     *
     * @mbggenerated
     */
    private String goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.goods_name:��Ʒ���
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.goods_title:��Ʒ����
     *
     * @mbggenerated
     */
    private String goodsTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.queue_no:�ں� 
     *
     * @mbggenerated
     */
    private Integer queueNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.create_time: ����ʱ��
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.end_time:�����ʱ��
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.goods_price:��Ʒ��ֵ
     *
     * @mbggenerated
     */
    private Integer goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.buy_num: �����˴�
     *
     * @mbggenerated
     */
    private Integer buyNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.total_buy_num:���蹺���˴�
     *
     * @mbggenerated
     */
    private Integer totalBuyNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.prize_no: �н����
     *
     * @mbggenerated
     */
    private String prizeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.winner_member_id:�н���ԱID
     *
     * @mbggenerated
     */
    private String winnerMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.winner_member_account: �н���Ա�˺�
     *
     * @mbggenerated
     */
    private String winnerMemberAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.winner_draw_num:�н��˲������
     *
     * @mbggenerated
     */
    private Integer winnerDrawNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.last_order_time:����򶩵�ʱ��
     *
     * @mbggenerated
     */
    private Date lastOrderTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.Id
     *
     * @return the value of activity.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.Id
     *
     * @param id the value for activity.Id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.goods_id
     *
     * @return the value of activity.goods_id
     *
     * @mbggenerated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.goods_id
     *
     * @param goodsId the value for activity.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.goods_name
     *
     * @return the value of activity.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.goods_name
     *
     * @param goodsName the value for activity.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.goods_title
     *
     * @return the value of activity.goods_title
     *
     * @mbggenerated
     */
    public String getGoodsTitle() {
        return goodsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.goods_title
     *
     * @param goodsTitle the value for activity.goods_title
     *
     * @mbggenerated
     */
    public void setGoodsTitle(String goodsTitle) {
        this.goodsTitle = goodsTitle == null ? null : goodsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.queue_no
     *
     * @return the value of activity.queue_no
     *
     * @mbggenerated
     */
    public Integer getQueueNo() {
        return queueNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.queue_no
     *
     * @param queueNo the value for activity.queue_no
     *
     * @mbggenerated
     */
    public void setQueueNo(Integer queueNo) {
        this.queueNo = queueNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.create_time
     *
     * @return the value of activity.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.create_time
     *
     * @param createTime the value for activity.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.end_time
     *
     * @return the value of activity.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.end_time
     *
     * @param endTime the value for activity.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.goods_price
     *
     * @return the value of activity.goods_price
     *
     * @mbggenerated
     */
    public Integer getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.goods_price
     *
     * @param goodsPrice the value for activity.goods_price
     *
     * @mbggenerated
     */
    public void setGoodsPrice(Integer goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.buy_num
     *
     * @return the value of activity.buy_num
     *
     * @mbggenerated
     */
    public Integer getBuyNum() {
        return buyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.buy_num
     *
     * @param buyNum the value for activity.buy_num
     *
     * @mbggenerated
     */
    public void setBuyNum(Integer buyNum) {
        this.buyNum = buyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.total_buy_num
     *
     * @return the value of activity.total_buy_num
     *
     * @mbggenerated
     */
    public Integer getTotalBuyNum() {
        return totalBuyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.total_buy_num
     *
     * @param totalBuyNum the value for activity.total_buy_num
     *
     * @mbggenerated
     */
    public void setTotalBuyNum(Integer totalBuyNum) {
        this.totalBuyNum = totalBuyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.prize_no
     *
     * @return the value of activity.prize_no
     *
     * @mbggenerated
     */
    public String getPrizeNo() {
        return prizeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.prize_no
     *
     * @param prizeNo the value for activity.prize_no
     *
     * @mbggenerated
     */
    public void setPrizeNo(String prizeNo) {
        this.prizeNo = prizeNo == null ? null : prizeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.winner_member_id
     *
     * @return the value of activity.winner_member_id
     *
     * @mbggenerated
     */
    public String getWinnerMemberId() {
        return winnerMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.winner_member_id
     *
     * @param winnerMemberId the value for activity.winner_member_id
     *
     * @mbggenerated
     */
    public void setWinnerMemberId(String winnerMemberId) {
        this.winnerMemberId = winnerMemberId == null ? null : winnerMemberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.winner_member_account
     *
     * @return the value of activity.winner_member_account
     *
     * @mbggenerated
     */
    public String getWinnerMemberAccount() {
        return winnerMemberAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.winner_member_account
     *
     * @param winnerMemberAccount the value for activity.winner_member_account
     *
     * @mbggenerated
     */
    public void setWinnerMemberAccount(String winnerMemberAccount) {
        this.winnerMemberAccount = winnerMemberAccount == null ? null : winnerMemberAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.winner_draw_num
     *
     * @return the value of activity.winner_draw_num
     *
     * @mbggenerated
     */
    public Integer getWinnerDrawNum() {
        return winnerDrawNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.winner_draw_num
     *
     * @param winnerDrawNum the value for activity.winner_draw_num
     *
     * @mbggenerated
     */
    public void setWinnerDrawNum(Integer winnerDrawNum) {
        this.winnerDrawNum = winnerDrawNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.last_order_time
     *
     * @return the value of activity.last_order_time
     *
     * @mbggenerated
     */
    public Date getLastOrderTime() {
        return lastOrderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.last_order_time
     *
     * @param lastOrderTime the value for activity.last_order_time
     *
     * @mbggenerated
     */
    public void setLastOrderTime(Date lastOrderTime) {
        this.lastOrderTime = lastOrderTime;
    }
}