package com.yungou.o2o.center.manager.model;

import java.io.Serializable;

public class ActivityResult implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -5957823028937359846L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_result.Id:
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_result.activity_id:
     *
     * @mbggenerated
     */
    private String activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_result.order_id:
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_result.Id
     *
     * @return the value of activity_result.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_result.Id
     *
     * @param id the value for activity_result.Id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_result.activity_id
     *
     * @return the value of activity_result.activity_id
     *
     * @mbggenerated
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_result.activity_id
     *
     * @param activityId the value for activity_result.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId == null ? null : activityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_result.order_id
     *
     * @return the value of activity_result.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_result.order_id
     *
     * @param orderId the value for activity_result.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }
}