package com.yungou.o2o.center.manager.model;

import java.io.Serializable;
import java.util.Date;

public class CircleTopic implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 4321558234804393719L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle_topic.Id:���
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle_topic.circle_id:Ȧ��ID
     *
     * @mbggenerated
     */
    private String circleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle_topic.member_id:��ԱID
     *
     * @mbggenerated
     */
    private String memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle_topic.member_account:��Ա�˺�
     *
     * @mbggenerated
     */
    private String memberAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle_topic.topic_name: �������
     *
     * @mbggenerated
     */
    private String topicName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle_topic.topic_desc:��������
     *
     * @mbggenerated
     */
    private String topicDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle_topic.create_time:����ʱ��
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle_topic.creator: ������
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle_topic.good_num:������
     *
     * @mbggenerated
     */
    private Integer goodNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle_topic.Id
     *
     * @return the value of circle_topic.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle_topic.Id
     *
     * @param id the value for circle_topic.Id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle_topic.circle_id
     *
     * @return the value of circle_topic.circle_id
     *
     * @mbggenerated
     */
    public String getCircleId() {
        return circleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle_topic.circle_id
     *
     * @param circleId the value for circle_topic.circle_id
     *
     * @mbggenerated
     */
    public void setCircleId(String circleId) {
        this.circleId = circleId == null ? null : circleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle_topic.member_id
     *
     * @return the value of circle_topic.member_id
     *
     * @mbggenerated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle_topic.member_id
     *
     * @param memberId the value for circle_topic.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle_topic.member_account
     *
     * @return the value of circle_topic.member_account
     *
     * @mbggenerated
     */
    public String getMemberAccount() {
        return memberAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle_topic.member_account
     *
     * @param memberAccount the value for circle_topic.member_account
     *
     * @mbggenerated
     */
    public void setMemberAccount(String memberAccount) {
        this.memberAccount = memberAccount == null ? null : memberAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle_topic.topic_name
     *
     * @return the value of circle_topic.topic_name
     *
     * @mbggenerated
     */
    public String getTopicName() {
        return topicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle_topic.topic_name
     *
     * @param topicName the value for circle_topic.topic_name
     *
     * @mbggenerated
     */
    public void setTopicName(String topicName) {
        this.topicName = topicName == null ? null : topicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle_topic.topic_desc
     *
     * @return the value of circle_topic.topic_desc
     *
     * @mbggenerated
     */
    public String getTopicDesc() {
        return topicDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle_topic.topic_desc
     *
     * @param topicDesc the value for circle_topic.topic_desc
     *
     * @mbggenerated
     */
    public void setTopicDesc(String topicDesc) {
        this.topicDesc = topicDesc == null ? null : topicDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle_topic.create_time
     *
     * @return the value of circle_topic.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle_topic.create_time
     *
     * @param createTime the value for circle_topic.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle_topic.creator
     *
     * @return the value of circle_topic.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle_topic.creator
     *
     * @param creator the value for circle_topic.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle_topic.good_num
     *
     * @return the value of circle_topic.good_num
     *
     * @mbggenerated
     */
    public Integer getGoodNum() {
        return goodNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle_topic.good_num
     *
     * @param goodNum the value for circle_topic.good_num
     *
     * @mbggenerated
     */
    public void setGoodNum(Integer goodNum) {
        this.goodNum = goodNum;
    }
}