package com.yungou.o2o.center.manager.model;

import java.io.Serializable;
import java.util.Date;

public class Commission implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1032548629904490477L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission.Id:���
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission.member_id:��ԱID
     *
     * @mbggenerated
     */
    private String memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission.total_commission:�ܹ���ȡӶ��
     *
     * @mbggenerated
     */
    private Double totalCommission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission.fetch_commission:����ȡӶ��
     *
     * @mbggenerated
     */
    private Double fetchCommission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission.create_time:����ʱ��
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission.Id
     *
     * @return the value of commission.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission.Id
     *
     * @param id the value for commission.Id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission.member_id
     *
     * @return the value of commission.member_id
     *
     * @mbggenerated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission.member_id
     *
     * @param memberId the value for commission.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission.total_commission
     *
     * @return the value of commission.total_commission
     *
     * @mbggenerated
     */
    public Double getTotalCommission() {
        return totalCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission.total_commission
     *
     * @param totalCommission the value for commission.total_commission
     *
     * @mbggenerated
     */
    public void setTotalCommission(Double totalCommission) {
        this.totalCommission = totalCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission.fetch_commission
     *
     * @return the value of commission.fetch_commission
     *
     * @mbggenerated
     */
    public Double getFetchCommission() {
        return fetchCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission.fetch_commission
     *
     * @param fetchCommission the value for commission.fetch_commission
     *
     * @mbggenerated
     */
    public void setFetchCommission(Double fetchCommission) {
        this.fetchCommission = fetchCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission.create_time
     *
     * @return the value of commission.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission.create_time
     *
     * @param createTime the value for commission.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}