package com.yungou.o2o.center.manager.model;

import java.io.Serializable;
import java.util.Date;

public class CommissionDetail implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -2706052243296021909L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.Id:���
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.member_id:��ԱID ��ԱID
     *
     * @mbggenerated
     */
    private String memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.invite_member_id:������ID ������ID
     *
     * @mbggenerated
     */
    private String inviteMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.order_id:����ID ����ID
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.create_time:����ʱ�� ����ʱ��
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.commission_value:Ӷ��ֵ Ӷ��ֵ
     *
     * @mbggenerated
     */
    private Double commissionValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commission_detail.commission_id:Ӷ��ID Ӷ��ID
     *
     * @mbggenerated
     */
    private String commissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.Id
     *
     * @return the value of commission_detail.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.Id
     *
     * @param id the value for commission_detail.Id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.member_id
     *
     * @return the value of commission_detail.member_id
     *
     * @mbggenerated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.member_id
     *
     * @param memberId the value for commission_detail.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.invite_member_id
     *
     * @return the value of commission_detail.invite_member_id
     *
     * @mbggenerated
     */
    public String getInviteMemberId() {
        return inviteMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.invite_member_id
     *
     * @param inviteMemberId the value for commission_detail.invite_member_id
     *
     * @mbggenerated
     */
    public void setInviteMemberId(String inviteMemberId) {
        this.inviteMemberId = inviteMemberId == null ? null : inviteMemberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.order_id
     *
     * @return the value of commission_detail.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.order_id
     *
     * @param orderId the value for commission_detail.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.create_time
     *
     * @return the value of commission_detail.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.create_time
     *
     * @param createTime the value for commission_detail.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.commission_value
     *
     * @return the value of commission_detail.commission_value
     *
     * @mbggenerated
     */
    public Double getCommissionValue() {
        return commissionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.commission_value
     *
     * @param commissionValue the value for commission_detail.commission_value
     *
     * @mbggenerated
     */
    public void setCommissionValue(Double commissionValue) {
        this.commissionValue = commissionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commission_detail.commission_id
     *
     * @return the value of commission_detail.commission_id
     *
     * @mbggenerated
     */
    public String getCommissionId() {
        return commissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commission_detail.commission_id
     *
     * @param commissionId the value for commission_detail.commission_id
     *
     * @mbggenerated
     */
    public void setCommissionId(String commissionId) {
        this.commissionId = commissionId == null ? null : commissionId.trim();
    }
}