package com.yungou.o2o.center.manager.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class Goods implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -8105128613427052009L;

	
	private List<GoodsPic> goodsPicList;
	
	public List<GoodsPic> getGoodsPicList() {
		return goodsPicList;
	}

	public void setGoodsPicList(List<GoodsPic> goodsPicList) {
		this.goodsPicList = goodsPicList;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.Id:��� ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_name:��Ʒ��� ��Ʒ���
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_code:��Ʒ���� ��Ʒ����
     *
     * @mbggenerated
     */
    private String goodsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.category_id:����ID ����ID
     *
     * @mbggenerated
     */
    private String categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.brand_id:Ʒ��ID Ʒ��ID
     *
     * @mbggenerated
     */
    private String brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.status:״̬ ״̬1�ϼ�2�¼�
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_desc:��Ʒ���� ��Ʒ����
     *
     * @mbggenerated
     */
    private String goodsDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.creator:������ ������
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.create_time:����ʱ�� ����ʱ��
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.update_time:�޸�ʱ�� �޸�ʱ��
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_price:��Ʒ�۸� ��Ʒ�۸�
     *
     * @mbggenerated
     */
    private Integer goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.limit_times:���ƴ��� ���ƴ���
     *
     * @mbggenerated
     */
    private Integer limitTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.queue_num:������ ������
     *
     * @mbggenerated
     */
    private Integer queueNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.is_recommend:�Ƿ��Ƽ� �Ƿ��Ƽ�  1�� 2��
     *
     * @mbggenerated
     */
    private Integer isRecommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.cost_price:�ɱ��� �ɱ���
     *
     * @mbggenerated
     */
    private Double costPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.queue_no:��ǰ�ں� ��ǰ�ں�
     *
     * @mbggenerated
     */
    private Integer queueNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_title:��Ʒ���� ��Ʒ����
     *
     * @mbggenerated
     */
    private String goodsTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.Id
     *
     * @return the value of goods.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.Id
     *
     * @param id the value for goods.Id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_name
     *
     * @return the value of goods.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_name
     *
     * @param goodsName the value for goods.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_code
     *
     * @return the value of goods.goods_code
     *
     * @mbggenerated
     */
    public String getGoodsCode() {
        return goodsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_code
     *
     * @param goodsCode the value for goods.goods_code
     *
     * @mbggenerated
     */
    public void setGoodsCode(String goodsCode) {
        this.goodsCode = goodsCode == null ? null : goodsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.category_id
     *
     * @return the value of goods.category_id
     *
     * @mbggenerated
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.category_id
     *
     * @param categoryId the value for goods.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.brand_id
     *
     * @return the value of goods.brand_id
     *
     * @mbggenerated
     */
    public String getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.brand_id
     *
     * @param brandId the value for goods.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(String brandId) {
        this.brandId = brandId == null ? null : brandId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.status
     *
     * @return the value of goods.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.status
     *
     * @param status the value for goods.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_desc
     *
     * @return the value of goods.goods_desc
     *
     * @mbggenerated
     */
    public String getGoodsDesc() {
        return goodsDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_desc
     *
     * @param goodsDesc the value for goods.goods_desc
     *
     * @mbggenerated
     */
    public void setGoodsDesc(String goodsDesc) {
        this.goodsDesc = goodsDesc == null ? null : goodsDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.creator
     *
     * @return the value of goods.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.creator
     *
     * @param creator the value for goods.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.create_time
     *
     * @return the value of goods.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.create_time
     *
     * @param createTime the value for goods.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.update_time
     *
     * @return the value of goods.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.update_time
     *
     * @param updateTime the value for goods.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_price
     *
     * @return the value of goods.goods_price
     *
     * @mbggenerated
     */
    public Integer getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_price
     *
     * @param goodsPrice the value for goods.goods_price
     *
     * @mbggenerated
     */
    public void setGoodsPrice(Integer goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.limit_times
     *
     * @return the value of goods.limit_times
     *
     * @mbggenerated
     */
    public Integer getLimitTimes() {
        return limitTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.limit_times
     *
     * @param limitTimes the value for goods.limit_times
     *
     * @mbggenerated
     */
    public void setLimitTimes(Integer limitTimes) {
        this.limitTimes = limitTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.queue_num
     *
     * @return the value of goods.queue_num
     *
     * @mbggenerated
     */
    public Integer getQueueNum() {
        return queueNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.queue_num
     *
     * @param queueNum the value for goods.queue_num
     *
     * @mbggenerated
     */
    public void setQueueNum(Integer queueNum) {
        this.queueNum = queueNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.is_recommend
     *
     * @return the value of goods.is_recommend
     *
     * @mbggenerated
     */
    public Integer getIsRecommend() {
        return isRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.is_recommend
     *
     * @param isRecommend the value for goods.is_recommend
     *
     * @mbggenerated
     */
    public void setIsRecommend(Integer isRecommend) {
        this.isRecommend = isRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.cost_price
     *
     * @return the value of goods.cost_price
     *
     * @mbggenerated
     */
    public Double getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.cost_price
     *
     * @param costPrice the value for goods.cost_price
     *
     * @mbggenerated
     */
    public void setCostPrice(Double costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.queue_no
     *
     * @return the value of goods.queue_no
     *
     * @mbggenerated
     */
    public Integer getQueueNo() {
        return queueNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.queue_no
     *
     * @param queueNo the value for goods.queue_no
     *
     * @mbggenerated
     */
    public void setQueueNo(Integer queueNo) {
        this.queueNo = queueNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_title
     *
     * @return the value of goods.goods_title
     *
     * @mbggenerated
     */
    public String getGoodsTitle() {
        return goodsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_title
     *
     * @param goodsTitle the value for goods.goods_title
     *
     * @mbggenerated
     */
    public void setGoodsTitle(String goodsTitle) {
        this.goodsTitle = goodsTitle == null ? null : goodsTitle.trim();
    }
}