package com.yungou.o2o.center.manager.model;

import java.io.Serializable;
import java.util.Date;

public class HomePagePic implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -7370905586192060678L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_page_pic.Id:
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_page_pic.pic_name:
     *
     * @mbggenerated
     */
    private String picName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_page_pic.pic_url:
     *
     * @mbggenerated
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_page_pic.pic_link:
     *
     * @mbggenerated
     */
    private String picLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_page_pic.sort_value:
     *
     * @mbggenerated
     */
    private Integer sortValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_page_pic.create_time:
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_page_pic.Id
     *
     * @return the value of home_page_pic.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_page_pic.Id
     *
     * @param id the value for home_page_pic.Id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_page_pic.pic_name
     *
     * @return the value of home_page_pic.pic_name
     *
     * @mbggenerated
     */
    public String getPicName() {
        return picName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_page_pic.pic_name
     *
     * @param picName the value for home_page_pic.pic_name
     *
     * @mbggenerated
     */
    public void setPicName(String picName) {
        this.picName = picName == null ? null : picName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_page_pic.pic_url
     *
     * @return the value of home_page_pic.pic_url
     *
     * @mbggenerated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_page_pic.pic_url
     *
     * @param picUrl the value for home_page_pic.pic_url
     *
     * @mbggenerated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_page_pic.pic_link
     *
     * @return the value of home_page_pic.pic_link
     *
     * @mbggenerated
     */
    public String getPicLink() {
        return picLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_page_pic.pic_link
     *
     * @param picLink the value for home_page_pic.pic_link
     *
     * @mbggenerated
     */
    public void setPicLink(String picLink) {
        this.picLink = picLink == null ? null : picLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_page_pic.sort_value
     *
     * @return the value of home_page_pic.sort_value
     *
     * @mbggenerated
     */
    public Integer getSortValue() {
        return sortValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_page_pic.sort_value
     *
     * @param sortValue the value for home_page_pic.sort_value
     *
     * @mbggenerated
     */
    public void setSortValue(Integer sortValue) {
        this.sortValue = sortValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_page_pic.create_time
     *
     * @return the value of home_page_pic.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_page_pic.create_time
     *
     * @param createTime the value for home_page_pic.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}