package com.yungou.o2o.center.manager.model;

import java.io.Serializable;
import java.util.Date;

public class MemberSharePic implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1746092829725998286L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_share_pic.Id:
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_share_pic.member_share_id:
     *
     * @mbggenerated
     */
    private String memberShareId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_share_pic.pic_url:
     *
     * @mbggenerated
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_share_pic.sort_value:
     *
     * @mbggenerated
     */
    private Integer sortValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_share_pic.create_time:
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_share_pic.Id
     *
     * @return the value of member_share_pic.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_share_pic.Id
     *
     * @param id the value for member_share_pic.Id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_share_pic.member_share_id
     *
     * @return the value of member_share_pic.member_share_id
     *
     * @mbggenerated
     */
    public String getMemberShareId() {
        return memberShareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_share_pic.member_share_id
     *
     * @param memberShareId the value for member_share_pic.member_share_id
     *
     * @mbggenerated
     */
    public void setMemberShareId(String memberShareId) {
        this.memberShareId = memberShareId == null ? null : memberShareId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_share_pic.pic_url
     *
     * @return the value of member_share_pic.pic_url
     *
     * @mbggenerated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_share_pic.pic_url
     *
     * @param picUrl the value for member_share_pic.pic_url
     *
     * @mbggenerated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_share_pic.sort_value
     *
     * @return the value of member_share_pic.sort_value
     *
     * @mbggenerated
     */
    public Integer getSortValue() {
        return sortValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_share_pic.sort_value
     *
     * @param sortValue the value for member_share_pic.sort_value
     *
     * @mbggenerated
     */
    public void setSortValue(Integer sortValue) {
        this.sortValue = sortValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_share_pic.create_time
     *
     * @return the value of member_share_pic.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_share_pic.create_time
     *
     * @param createTime the value for member_share_pic.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}