package com.yungou.o2o.center.manager.model;

import java.io.Serializable;
import java.util.Date;

public class MemberBankDetail implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -3053432912000971232L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_bank_detail.Id:��� ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_bank_detail.member_id:��ԱID ��ԱID
     *
     * @mbggenerated
     */
    private String memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_bank_detail.member_bank_id:��Ա����ID
     *
     * @mbggenerated
     */
    private String memberBankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_bank_detail.change_type:������� 1 ���  2 �˺����
     *
     * @mbggenerated
     */
    private Integer changeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_bank_detail.change_value: �仯ֵ
     *
     * @mbggenerated
     */
    private Integer changeValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_bank_detail.change_desc: �������
     *
     * @mbggenerated
     */
    private String changeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_bank_detail.create_time:����ʱ��
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_bank_detail.Id
     *
     * @return the value of member_bank_detail.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_bank_detail.Id
     *
     * @param id the value for member_bank_detail.Id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_bank_detail.member_id
     *
     * @return the value of member_bank_detail.member_id
     *
     * @mbggenerated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_bank_detail.member_id
     *
     * @param memberId the value for member_bank_detail.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_bank_detail.member_bank_id
     *
     * @return the value of member_bank_detail.member_bank_id
     *
     * @mbggenerated
     */
    public String getMemberBankId() {
        return memberBankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_bank_detail.member_bank_id
     *
     * @param memberBankId the value for member_bank_detail.member_bank_id
     *
     * @mbggenerated
     */
    public void setMemberBankId(String memberBankId) {
        this.memberBankId = memberBankId == null ? null : memberBankId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_bank_detail.change_type
     *
     * @return the value of member_bank_detail.change_type
     *
     * @mbggenerated
     */
    public Integer getChangeType() {
        return changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_bank_detail.change_type
     *
     * @param changeType the value for member_bank_detail.change_type
     *
     * @mbggenerated
     */
    public void setChangeType(Integer changeType) {
        this.changeType = changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_bank_detail.change_value
     *
     * @return the value of member_bank_detail.change_value
     *
     * @mbggenerated
     */
    public Integer getChangeValue() {
        return changeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_bank_detail.change_value
     *
     * @param changeValue the value for member_bank_detail.change_value
     *
     * @mbggenerated
     */
    public void setChangeValue(Integer changeValue) {
        this.changeValue = changeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_bank_detail.change_desc
     *
     * @return the value of member_bank_detail.change_desc
     *
     * @mbggenerated
     */
    public String getChangeDesc() {
        return changeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_bank_detail.change_desc
     *
     * @param changeDesc the value for member_bank_detail.change_desc
     *
     * @mbggenerated
     */
    public void setChangeDesc(String changeDesc) {
        this.changeDesc = changeDesc == null ? null : changeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_bank_detail.create_time
     *
     * @return the value of member_bank_detail.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_bank_detail.create_time
     *
     * @param createTime the value for member_bank_detail.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}