package com.yungou.o2o.center.manager.model;

import java.io.Serializable;
import java.util.Date;

public class MemberBase implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 7063710644759450950L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_base.Id:ID ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_base.mobile_phone:�ƶ��绰
     *
     * @mbggenerated
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_base.member_account:��Ա�˺� 
     *
     * @mbggenerated
     */
    private String memberAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_base.member_password:��Ա����
     *
     * @mbggenerated
     */
    private String memberPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_base.member_name:��Ա��� 
     *
     * @mbggenerated
     */
    private String memberName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_base.member_image:��Աͷ��ͼƬ
     *
     * @mbggenerated
     */
    private String memberImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_base.member_email:��Ա���� 
     *
     * @mbggenerated
     */
    private String memberEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_base.qq_no:QQ����
     *
     * @mbggenerated
     */
    private String qqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_base.open_id:΢��ID
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_base.birthday:����
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_base.create_time:����ʱ��
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_base.update_time:�޸�ʱ��
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_base.register_ip:ע��IP
     *
     * @mbggenerated
     */
    private String registerIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_base.registre_source:ע����Դ
     *
     * @mbggenerated
     */
    private String registreSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_base.status:״̬1 �� 2��
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_base.mobile_validate:�ֻ���֤ 1�� 2��
     *
     * @mbggenerated
     */
    private Integer mobileValidate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_base.email_validate:������֤1��֤2��
     *
     * @mbggenerated
     */
    private Integer emailValidate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_base.remark:��ע
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_base.member_level:��Ա����
     *
     * @mbggenerated
     */
    private String memberLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_base.invite_member_id:������ID
     *
     * @mbggenerated
     */
    private String inviteMemberId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_base.Id
     *
     * @return the value of member_base.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_base.Id
     *
     * @param id the value for member_base.Id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_base.mobile_phone
     *
     * @return the value of member_base.mobile_phone
     *
     * @mbggenerated
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_base.mobile_phone
     *
     * @param mobilePhone the value for member_base.mobile_phone
     *
     * @mbggenerated
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_base.member_account
     *
     * @return the value of member_base.member_account
     *
     * @mbggenerated
     */
    public String getMemberAccount() {
        return memberAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_base.member_account
     *
     * @param memberAccount the value for member_base.member_account
     *
     * @mbggenerated
     */
    public void setMemberAccount(String memberAccount) {
        this.memberAccount = memberAccount == null ? null : memberAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_base.member_password
     *
     * @return the value of member_base.member_password
     *
     * @mbggenerated
     */
    public String getMemberPassword() {
        return memberPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_base.member_password
     *
     * @param memberPassword the value for member_base.member_password
     *
     * @mbggenerated
     */
    public void setMemberPassword(String memberPassword) {
        this.memberPassword = memberPassword == null ? null : memberPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_base.member_name
     *
     * @return the value of member_base.member_name
     *
     * @mbggenerated
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_base.member_name
     *
     * @param memberName the value for member_base.member_name
     *
     * @mbggenerated
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_base.member_image
     *
     * @return the value of member_base.member_image
     *
     * @mbggenerated
     */
    public String getMemberImage() {
        return memberImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_base.member_image
     *
     * @param memberImage the value for member_base.member_image
     *
     * @mbggenerated
     */
    public void setMemberImage(String memberImage) {
        this.memberImage = memberImage == null ? null : memberImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_base.member_email
     *
     * @return the value of member_base.member_email
     *
     * @mbggenerated
     */
    public String getMemberEmail() {
        return memberEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_base.member_email
     *
     * @param memberEmail the value for member_base.member_email
     *
     * @mbggenerated
     */
    public void setMemberEmail(String memberEmail) {
        this.memberEmail = memberEmail == null ? null : memberEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_base.qq_no
     *
     * @return the value of member_base.qq_no
     *
     * @mbggenerated
     */
    public String getQqNo() {
        return qqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_base.qq_no
     *
     * @param qqNo the value for member_base.qq_no
     *
     * @mbggenerated
     */
    public void setQqNo(String qqNo) {
        this.qqNo = qqNo == null ? null : qqNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_base.open_id
     *
     * @return the value of member_base.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_base.open_id
     *
     * @param openId the value for member_base.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_base.birthday
     *
     * @return the value of member_base.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_base.birthday
     *
     * @param birthday the value for member_base.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_base.create_time
     *
     * @return the value of member_base.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_base.create_time
     *
     * @param createTime the value for member_base.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_base.update_time
     *
     * @return the value of member_base.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_base.update_time
     *
     * @param updateTime the value for member_base.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_base.register_ip
     *
     * @return the value of member_base.register_ip
     *
     * @mbggenerated
     */
    public String getRegisterIp() {
        return registerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_base.register_ip
     *
     * @param registerIp the value for member_base.register_ip
     *
     * @mbggenerated
     */
    public void setRegisterIp(String registerIp) {
        this.registerIp = registerIp == null ? null : registerIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_base.registre_source
     *
     * @return the value of member_base.registre_source
     *
     * @mbggenerated
     */
    public String getRegistreSource() {
        return registreSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_base.registre_source
     *
     * @param registreSource the value for member_base.registre_source
     *
     * @mbggenerated
     */
    public void setRegistreSource(String registreSource) {
        this.registreSource = registreSource == null ? null : registreSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_base.status
     *
     * @return the value of member_base.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_base.status
     *
     * @param status the value for member_base.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_base.mobile_validate
     *
     * @return the value of member_base.mobile_validate
     *
     * @mbggenerated
     */
    public Integer getMobileValidate() {
        return mobileValidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_base.mobile_validate
     *
     * @param mobileValidate the value for member_base.mobile_validate
     *
     * @mbggenerated
     */
    public void setMobileValidate(Integer mobileValidate) {
        this.mobileValidate = mobileValidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_base.email_validate
     *
     * @return the value of member_base.email_validate
     *
     * @mbggenerated
     */
    public Integer getEmailValidate() {
        return emailValidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_base.email_validate
     *
     * @param emailValidate the value for member_base.email_validate
     *
     * @mbggenerated
     */
    public void setEmailValidate(Integer emailValidate) {
        this.emailValidate = emailValidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_base.remark
     *
     * @return the value of member_base.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_base.remark
     *
     * @param remark the value for member_base.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_base.member_level
     *
     * @return the value of member_base.member_level
     *
     * @mbggenerated
     */
    public String getMemberLevel() {
        return memberLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_base.member_level
     *
     * @param memberLevel the value for member_base.member_level
     *
     * @mbggenerated
     */
    public void setMemberLevel(String memberLevel) {
        this.memberLevel = memberLevel == null ? null : memberLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_base.invite_member_id
     *
     * @return the value of member_base.invite_member_id
     *
     * @mbggenerated
     */
    public String getInviteMemberId() {
        return inviteMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_base.invite_member_id
     *
     * @param inviteMemberId the value for member_base.invite_member_id
     *
     * @mbggenerated
     */
    public void setInviteMemberId(String inviteMemberId) {
        this.inviteMemberId = inviteMemberId == null ? null : inviteMemberId.trim();
    }
}