package com.yungou.o2o.center.manager.model;

import java.io.Serializable;
import java.util.Date;

public class MemberCircle implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -4476703093366919502L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_circle.Id:
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_circle.circle_name:
     *
     * @mbggenerated
     */
    private String circleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_circle.circle_desc:
     *
     * @mbggenerated
     */
    private String circleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_circle.create_time:
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_circle.STATUS:
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_circle.Id
     *
     * @return the value of member_circle.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_circle.Id
     *
     * @param id the value for member_circle.Id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_circle.circle_name
     *
     * @return the value of member_circle.circle_name
     *
     * @mbggenerated
     */
    public String getCircleName() {
        return circleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_circle.circle_name
     *
     * @param circleName the value for member_circle.circle_name
     *
     * @mbggenerated
     */
    public void setCircleName(String circleName) {
        this.circleName = circleName == null ? null : circleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_circle.circle_desc
     *
     * @return the value of member_circle.circle_desc
     *
     * @mbggenerated
     */
    public String getCircleDesc() {
        return circleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_circle.circle_desc
     *
     * @param circleDesc the value for member_circle.circle_desc
     *
     * @mbggenerated
     */
    public void setCircleDesc(String circleDesc) {
        this.circleDesc = circleDesc == null ? null : circleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_circle.create_time
     *
     * @return the value of member_circle.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_circle.create_time
     *
     * @param createTime the value for member_circle.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_circle.STATUS
     *
     * @return the value of member_circle.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_circle.STATUS
     *
     * @param status the value for member_circle.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}