package com.yungou.o2o.center.manager.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class MemberShare implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 2709616735498371924L;

	
	private  List<MemberSharePic> memberSharePicList;
	
	public List<MemberSharePic> getMemberSharePicList() {
		return memberSharePicList;
	}

	public void setMemberSharePicList(List<MemberSharePic> memberSharePicList) {
		this.memberSharePicList = memberSharePicList;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_share.Id:���
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_share.member_id:��ԱID
     *
     * @mbggenerated
     */
    private String memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_share.member_account:��Ա�˺� ��Ա�˺�
     *
     * @mbggenerated
     */
    private String memberAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_share.order_id:����ID ����ID
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_share.share_title:������� �������
     *
     * @mbggenerated
     */
    private String shareTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_share.share_desc:�������� ��������
     *
     * @mbggenerated
     */
    private String shareDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_share.create_time:����ʱ�� ����ʱ��
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_share.click_num:������� �������
     *
     * @mbggenerated
     */
    private Integer clickNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_share.Id
     *
     * @return the value of member_share.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_share.Id
     *
     * @param id the value for member_share.Id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_share.member_id
     *
     * @return the value of member_share.member_id
     *
     * @mbggenerated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_share.member_id
     *
     * @param memberId the value for member_share.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_share.member_account
     *
     * @return the value of member_share.member_account
     *
     * @mbggenerated
     */
    public String getMemberAccount() {
        return memberAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_share.member_account
     *
     * @param memberAccount the value for member_share.member_account
     *
     * @mbggenerated
     */
    public void setMemberAccount(String memberAccount) {
        this.memberAccount = memberAccount == null ? null : memberAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_share.order_id
     *
     * @return the value of member_share.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_share.order_id
     *
     * @param orderId the value for member_share.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_share.share_title
     *
     * @return the value of member_share.share_title
     *
     * @mbggenerated
     */
    public String getShareTitle() {
        return shareTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_share.share_title
     *
     * @param shareTitle the value for member_share.share_title
     *
     * @mbggenerated
     */
    public void setShareTitle(String shareTitle) {
        this.shareTitle = shareTitle == null ? null : shareTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_share.share_desc
     *
     * @return the value of member_share.share_desc
     *
     * @mbggenerated
     */
    public String getShareDesc() {
        return shareDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_share.share_desc
     *
     * @param shareDesc the value for member_share.share_desc
     *
     * @mbggenerated
     */
    public void setShareDesc(String shareDesc) {
        this.shareDesc = shareDesc == null ? null : shareDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_share.create_time
     *
     * @return the value of member_share.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_share.create_time
     *
     * @param createTime the value for member_share.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_share.click_num
     *
     * @return the value of member_share.click_num
     *
     * @mbggenerated
     */
    public Integer getClickNum() {
        return clickNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_share.click_num
     *
     * @param clickNum the value for member_share.click_num
     *
     * @mbggenerated
     */
    public void setClickNum(Integer clickNum) {
        this.clickNum = clickNum;
    }
}