package com.yungou.o2o.center.manager.model;

import java.io.Serializable;

public class OrderTicket implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -604856821723359017L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_ticket.Id:
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_ticket.order_id:
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_ticket.ticket_no:
     *
     * @mbggenerated
     */
    private String ticketNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_ticket.Id
     *
     * @return the value of order_ticket.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_ticket.Id
     *
     * @param id the value for order_ticket.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_ticket.order_id
     *
     * @return the value of order_ticket.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_ticket.order_id
     *
     * @param orderId the value for order_ticket.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_ticket.ticket_no
     *
     * @return the value of order_ticket.ticket_no
     *
     * @mbggenerated
     */
    public String getTicketNo() {
        return ticketNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_ticket.ticket_no
     *
     * @param ticketNo the value for order_ticket.ticket_no
     *
     * @mbggenerated
     */
    public void setTicketNo(String ticketNo) {
        this.ticketNo = ticketNo == null ? null : ticketNo.trim();
    }
}